package it.unibas.tenet.model.dto.frontend;

import io.smallrye.common.constraint.NotNull;
import it.unibas.tenet.model.Cell;
import it.unibas.tenet.model.SemanticQuery;
import java.util.ArrayList;
import java.util.List;
import lombok.Data;
import org.bson.types.ObjectId;

@Data
public class EvidenceFrontendDTO {

    private ObjectId id;

    private boolean autoGenerated;

    private boolean negative;

    @NotNull
    List<Cell> cells;

    private List<String> sentences = new ArrayList<>();
    List<SemanticQuery> semanticQueries = new ArrayList<>();
}
