import { Cell } from "./cell";
import { SemanticQuery } from "./semanticquery";

export class Evidence {

  constructor(public cells: Cell[], public autoGenerated = false, public negative = false) {
  }

  public id?: string;

  public sentences?: string[];
  public semanticQueries?: SemanticQuery[];

}
