name: "tenet"
services:
  mongodb:
    image: mongo
    container_name: tenet-mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./tenet_mongo/data:/data/db
      - ./tenet_mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    # ports:
      # - 27017:27017

  postgres:
    image: postgres
    container_name: tenet-postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: tenet
    # ports:
    #   - 5432:5432

  engine:
    build:
      context: ../engine
    image: tenet-engine
    container_name: tenet-engine
    volumes:
      - ./tenet_engine/data:/usr/src/app/data
    ports:
      - 8000:8000
    depends_on:
      - postgres
    links:
      - postgres
      - ollama

  ollama:
    image: ollama/ollama
    # ports:
    #     - 11434:11434
    volumes:
        - ./tenet_ollama/ollama:/root/.ollama
        - ./tenet_ollama/entrypoint.sh:/entrypoint.sh
    container_name: tenet-ollama
    pull_policy: always
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]


volumes:
  tenet_mongo:

  tenet_engine:

