API_KEYS_GPT3 = ["YOUR_API_HERE"]
CACHE_DIR = "CACHE_DIR_FOR_GPT_REQUESTS"

LANGUAGE_MODEL_CHAT_GTP = "ChatGPT"
LANGUAGE_MODEL_GPT3 = "GPT3"
LANGUAGE_MODEL_T5 = "T5"
LANGUAGE_MODEL_CHAT_GTP_ERRORS = ["There is no data.", "FAILED"]

## ATTRIBUTE TYPE
NUMERICAL = "numerical"
CATEGORICAL = "categorical"

## OPERATIONS NAME
OPERATION_LOOKUP = "lookup"
OPERATION_COMPARISON = "comparison"
OPERATION_MIN = "min"
OPERATION_MAX = "max"
OPERATION_COUNT = "count"
OPERATION_GROUPING = "grouping"
OPERATION_SUM = "sum"
OPERATION_AVG = "avg"
OPERATION_FILTER = "filter"

## OPERATORS
OPERATOR_GT = ">"
OPERATOR_LT = "<"
OPERATOR_SAME = "="

## VALUE GENERATOR
STRATEGY_ACTIVE_DOMAIN = "ActiveDomain"
STRATEGY_LM_GENERATOR = "LMGenerator"
STATEGY_CHANGE_MIN = "ChangeMin"
STATEGY_CHANGE_MAX = "ChangeMax"