package it.unibas.tenet.model;

import java.util.ArrayList;
import java.util.List;
import lombok.Data;
import org.bson.types.ObjectId;

@Data
public class Evidence {

    private ObjectId id;

    private boolean autoGenerated;

    private boolean negative;

    List<Cell> cells = new ArrayList<>();
    
    List<String> sentences = new ArrayList<>();
    
    List<SemanticQuery> semanticQueries = new ArrayList<>();
}
