package it.unibas.tenet.model;

import io.quarkus.mongodb.panache.common.MongoEntity;
import java.util.List;
import lombok.Data;
import org.bson.types.ObjectId;

@MongoEntity(collection = "projects")
@Data
public class Project {

    private ObjectId id;

    private List<Evidence> evidence;

    private String name;

    // private ObjectId userId; 
    private Database database;

    private String query;

    public Evidence findUserEvidence() {
        return this.evidence.stream().filter(e -> !e.isAutoGenerated()).findAny().orElse(null);
    }

    public Evidence findEvidenceById(String evidenceId) {
        return this.evidence.stream().filter(e -> e.getId().toString().equals(evidenceId)).findAny().orElse(null);
    }

    public void resetProject() {
        this.evidence.clear();
        this.query = null;
        this.database.setNegativeTable(null);
    }
}
